title: Martin Hellkvist # your name (or website title) here
logo: "/images/logo_mh.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  martin.hellkvist@angstrom.uu.se 
  <br><br>
  I am a PhD student at the Division of Signals and Systems,
  Department of Electrical Engineering at Uppsala University. 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
